# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dnative -s settings.xml -DskipTests -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Cache@2
      inputs:
        key: '"maven" | "$(Agent.OS)" | **/pom.xml'
        restoreKeys: |
          "maven" | "$(Agent.OS)"
          "maven"
        path: $(MAVEN_CACHE_FOLDER)
      displayName: Cache Maven packages
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install $(MAVEN_OPTS)' # Activates the native profile
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '21' # Or your required JDK version
        mavenVersionOption: 'Default'
    - task: Bash@3
      inputs:
        script: |
          echo "Structure of the build directory:"
          ls -R $(Build.SourcesDirectory)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/main/docker/Dockerfile.native'
        tags: |
          $(tag)
